### ISSUE TITLE
add the ability to delete users who were invited as users, but didn't confirm

### ISSUE THREAD

**Issue by JohnTheodore** [lfepp/pd_user_deprovision#6]
I can invite a user into my pagerduty account, they don't confirm the email and signup. so they're active on my billing for pagerduty, but they're not listed in the userlist afaict.

The error I get is:

ValueError: Could not find user with email (u'bill@initech.com', u'DJVT18R').

Note, I can deprovision all the other full users who are active and confirmed.

**Comment by lfepp** [comment]
Hey @JohnTheodore sorry I didn't see this until now, haven't been checking enough. I no longer work at PagerDuty so you may want to get in touch with support@pagerduty.com about this, but I believe users who are added but have not yet accepted the email don't actually have a full user profile in the back-end, which is why you're not finding them. If I recall correctly, the email will not be queryable until the user confirms their email address, so we wouldn't be able to de-provision them via email and it'd have to be using their user ID directly or something along those lines. I'm not entirely sure if I'm right here so I'll do a little digging.

@Deconstrained do you have any insight into this?

**Comment by Deconstrained** [comment]
@JohnTheodore I was not able to reproduce this issue following these steps:

1.  Invite new user (using a trial account). In case it might actually matter: I used an existing email address but made it distinct by using an alias, i.e. `{username}+{alias}@{domain}` 
2. I did not activate the user by clicking the invitation link.
3. I ran the script (at revision d55744407312c0e0b941ebece4e9de87075db2a4, latest as of this writing)

**Comment by lfepp** [comment]
Thanks for taking a look @Deconstrained! The email existing without the alias shouldn't matter since that's just used as the `query` param for lookup.

@JohnTheodore I'm going to close out this issue since it sounds like it's fixed. If you're still seeing this issue, could you download the latest copy of the script and see if this fixes the issue? If it doesn't, let us know and we can re-open this issue and take a look at your issue.
